default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: beforegotothemoon_development

test:
  <<: *default
  database: beforegotothemoon_test

production:
  <<: *default
  database: beforegotothemoon_production
  username: beforegotothemoon
  password: <%= ENV['BEFOREGOTOTHEMOON_DATABASE_PASSWORD'] %>
